GRANT TEMP ON DATABASE LOJA_INTEGRADA TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO postgres;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO postgres;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO postgres;

CREATE TABLE PRODUCTS (
   ID INT PRIMARY KEY NOT NULL
);
INSERT INTO PRODUCTS (ID) VALUES (1);